language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

before_install:
  - docker build -t crystal-ball/eloquence .

script:
 - docker run crystal-ball/eloquence /bin/sh -c "cd /usr/src/app && npm test"

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
