language: node_js
node_js:
  # Use Atom's node version for compatibility testing
  - '10'

services:
  - docker

install:
  - docker build -t crystal-ball/eloquence .

script:
  -docker run crystal-ball/eloquence

# Release with Semantic after tests pass
deploy:
  provider: script
   # Prevent Travis from resetting working directory after build
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: master
