name: CI/CD
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: NPM Install
        uses: actions/npm@master
        with:
          args: ci
        env:
          CI: true
      - name: Test
        uses: actions/npm@master
        with:
          args: test
